language: elixir
cache:
  directories:
  - deps
services:
  - postgresql
addons:
  postgresql: "9.5"
elixir:
  - 1.3.0
otp_release:
  - 19.0
env:
  global:
    - MIX_ENV=test
before_install:
  # Expose MQ and DB to Docker container
  - sudo ./bin/ci/init-db.sh
script:
  # Install dependencies
  - "mix deps.get"
  # Run all tests except pending ones
  - "mix test --exclude pending --trace"
  # Submit code coverage report to Coveralls
  - "mix coveralls.travis"
  # Run static code analysis
  - "mix credo"
  # Check code style
  - "mix dogma"
